### ISSUE TITLE
NETS Guidelines Document

### ISSUE THREAD

**Issue by kam642** [Drexel-UHC/NETS#10]
Create a document for the UHC license of NETS (expected Aug 2023) the outlines the following:
1. Terminology to be used when referring to NETS/analytic files
2. Work flow and staff who will work on each step
3. Acknowledgements
4. Funding requirements for future usage

**Comment by kam642** [comment]
@JanaHirsch Can you please write a section that give the rules/guidelines/requirements for requesting UHC staff processing time for future NETS needs?

**Comment by JanaHirsch** [comment]
@kam642 I took a stab at writing this. I think it feels like it's missing stuff but this gives us somewhere to start. Lots of notes in here for you.
[Process_Notes_PI_NETS_Businesses_20230723.docx](https://github.com/Drexel-UHC/NETS/files/12140252/Process_Notes_PI_NETS_Businesses_20230723.docx)

**Comment by kam642** [comment]
@JanaHirsch I added to your file and renamed such that NETS is the first word in the file name to make it easier for me to find.
Focus on the parts highlighted in green. Ignore the yellow highlights - I need to go back and fill in that info.



[NETS_Process_Notes_PI_20230830.docx](https://github.com/Drexel-UHC/NETS/files/12479524/NETS_Process_Notes_PI_20230830.docx)

**Comment by sjmelly** [comment]
@kam642 @stfran22  I added some comments and edits. I proposed language for describing the establishment level analytic dataset as a SQL database. 

[NETS_Process_Notes_PI_20240206SM.docx](https://github.com/Drexel-UHC/NETS/files/14214641/NETS_Process_Notes_PI_20240206SM.docx)

**Comment by stfran22** [comment]
@sjmelly @kam642 Just added a few edits of my own. 

[NETS_Process_Notes_PI_20240208.docx](https://github.com/Drexel-UHC/NETS/files/14214723/NETS_Process_Notes_PI_20240208.docx)

**Comment by kam642** [comment]
@sjmelly @stfran22 Thanks!
I removed anywhere you put in exact details on the derived data itself (like stored in SQL, 2010 boundaries, etc). Those are things that could possibly change in what we derive and I would rather this be more generic to outline access so if those types of details change, we don't have to change them in this doc.

All of those details should be in the summary sheet. And this doc can just refer people to the summary doc so that should be most current with what we have available.

@sjmelly For your comment "Why is Food & Communities grant title included but other grants just funding source and grant number?" This acknowledgement went back and forth between Jana, Kelly Courts, Felice and they settled on this so I'm not changing it.

@sjmelly For you comment "Do we want to qualify this as for a study cohort of < X participants? Linkage to Electronic Health Records or Administrative Datasets (e.g. Medicare data) may be more time consuming"
Can you give me what X would be?

**Comment by kam642** [comment]
@stfran22 To finish this guidelines document, I need the link to the page for the BEDDN on the UHC data portal. Can you send to me when that is ready?

**Comment by stfran22** [comment]
https://data.uhcdata.org/dataset/beddn-info-sheet

@kam642 info sheet and catalogue have both been added to the portal. Let me know if you would like any edits to the portal pages and if they need to be added to the tracking sheet. Do we also want tract and zcta counts and densities files on the portal for Wednesday as well?

**Comment by kam642** [comment]
@stfran22 We can't put the data on the portal. We can't send to anyone until they complete the data request/DUA and agree to terms.

For BEDDN, rather than having the XLSX and PDF as separate "datasets" on the Portal, can you create one dataset page and include both file in one place? We also need to include the link to the Qualtrics survey. See the issue in the data portal update project.
@jannettim Can you help with this?

**Comment by sjmelly** [comment]
@stfran22 There's a typo in the tag "Envinroment". Should we add additional tags e,g, "Business Establishments"? Can we add it to the Built Environment Group? In the summary second line from the end "field" is missing the f

**Comment by stfran22** [comment]
> For BEDDN, rather than having the XLSX and PDF as separate "datasets" on the Portal, can you create one dataset page and include both file in one place? We also need to include the link to the Qualtrics survey. See the issue in the data portal update project. @jannettim Can you help with this?

I can take care of all of this! I'll update accordingly.

**Comment by kam642** [comment]
Done!
