### ISSUE TITLE
Create Analytic dataset for MESA Neighborhood summer students

### ISSUE THREAD

**Issue by sjmelly** [Drexel-UHC/NETS#12]

**Comment by sjmelly** [comment]
@stfran22  NETS Tract measures for selected categories 
@sjmelly demographic data from LTDB via RECVD for 2000 & 2010 and from UHC for ACS

**Comment by stfran22** [comment]
@sjmelly can we close this? seems like we'll just create more individual issues for students if necessary.

**Comment by sjmelly** [comment]
Yes I'll go ahead and close it.
