### ISSUE TITLE
Create dataset for geocoding NETS

### ISSUE THREAD

**Issue by sjmelly** [Drexel-UHC/NETS#2]
Unique locations used for categories. Python used to create .csv with DUNS_MOVE street address, city, state, zip, zip+4, first year, last year

**Comment by stfran22** [comment]
@sjmelly I just realized we have to run the SAS categorization scripts first so we have the full list of DunsNumbers to subset. Might need an overview with one of them in our meeting tomorrow morning.

**Comment by sjmelly** [comment]
@stfran22 geocoding_final20230602.txt includes records outside of the contiguous US. These should be removed
-We will want ArcGISPro to recognize ZIP and ZIP4 as strings. I created a schema.ini file for this in \Projects\NETS\Data\NETS2019_Python\SMExample DUNSMove has too many digits for a long integer so I made it a string with 11 characters. How may characters should we allow for GcAddress and GcCity?
-Do we want to group by GcAddress, GcCity, GcState GcZIP, and GcZIP4 and create a location ID before geocoding? For the  1,259,035 records for Pennsylvania the number of unique addresses is 894,337 so this might be worth doing.

**Comment by stfran22** [comment]
1. I'll remove records outside the contiguous US and send you an updated version.

2. I'm only seeing a max length of 30 characters for GcAddress and 20 characters for GcCity after removing trailing whitespace. Don Walls has Address set to 50 characters and City set to 30. I think we should stick with his specifications, in case we get a longer name in a future NETS vintage.

3. Clarifying - If we go forward with the location ID method we would need the Geocoding Input Dataset to have LocID, GcAddress, GcCity, GcState, GcZIP, GcZIP4. Then the LocID would be linked to DunsMove in the DunsYear DunsMove Key (columns would be: DunsYear, DunsMove, LocID)? Also should we just drop DunsNumber and MoveNum from the Geocoding Input Dataset because we have them in DunsMove?

**Comment by sjmelly** [comment]
Yes if we use location ID we will drop DunsYear and DunsMove from the Geocoding Input Dataset. [Actually we should probably call this Address ID to be consistent with our earlier work with InfoUSA data. More than one address ID could be geocoded to the same latitude and longitude which is what we were calling "locations" before. We can add Address ID to the DunsMove  dataset and use Address ID to link geocoding results back to DunsMove. I was thinking in might be useful to have minFirstYear and maxLastYear in the Geocoding Input Dataset since the older addresses might not geocode as well and we might want to look at that.

**Comment by stfran22** [comment]
Would you want GcFirstYear and GcLastYear in the Key or in the AddressID dataset?

**Comment by sjmelly** [comment]
Include minGcFirstYear and MaxGcLastYear in the Address ID dataset so that they will be included in the geocoding results
I was thinking we would just add address id to the existing DunsMove dataset which will include GcFirstYear and GcLastYear

**Comment by stfran22** [comment]
I am going to close this issue, as the dataset has been created. There is the "Addresses" table, which will be used as the geocoding input dataset. This can be linked to DunsMove, DunsNumber, GcFirstYear, and GcLastYear with the AddressID, which are all contained in the "DunsMove" table. Detail below taken from "\\files.drexel.edu\colleges\SOPH\Shared\UHC\Projects\NETS\Documentation\NETS Processing Documentation 20230614.docx". Some information is subject to change, please refer to latest version of NETS Processing Documentation for more details.


<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/stf45/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

<link rel=themeData
href="file:///C:/Users/stf45/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/stf45/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=EN-US style='tab-interval:.5in;word-wrap:break-word'>


<h3>Appendix L: Addresses <o:p></o:p></h3>

<p class=MsoNoSpacing><a name="_Hlk137213099"><u>Dataset name</u>:<b> Addresses
<o:p></o:p></b></a></p>

<p class=MsoNoSpacing><span style='mso-bookmark:_Hlk137213099'><u>Filename</u>:
AddressesYYYYMMDD.txt <o:p></o:p></span></p>

<p class=MsoNoSpacing><span style='mso-bookmark:_Hlk137213099'><u>Number of
records</u>: 23,254,660 <o:p></o:p></span></p>

<p class=MsoNoSpacing><span style='mso-bookmark:_Hlk137213099'><u>Number of
columns</u>: 6<o:p></o:p></span></p>

<p class=MsoNoSpacing><span style='mso-bookmark:_Hlk137213099'><u>Python file
that generated this file</u>: create_geocoding.py<o:p></o:p></span></p>

<span style='mso-bookmark:_Hlk137213099'></span>

<p class=MsoNoSpacing><o:p>&nbsp;</o:p></p>

<p class=MsoNoSpacing><o:p>&nbsp;</o:p></p>

<p class=MsoNoSpacing><span style='font-size:10.0pt'>Geocoding Input Dataset
Variable List<o:p></o:p></span></p>



Variable | Type | Description | Formula
-- | -- | -- | --
AddressID | String | Ten character unique ID for combination of GcAddress, GcCity,   GcState, GcZIP, GcZIP4. | “A” + nine-digit string, i.e. A000000001
GcAddress | String | Address of Location | = Company[Address]    OR   = Move[OriginAddress]
GcCity | String | City of Location | = Company[City] OR   Move[OriginCity]
GcState | String | State of Location | = Company[State]    OR   = Move[OriginState]
GcZIP | String | ZIP Code of Location | = Company[ZipCode]    OR   = Move[OriginZIP]
GcZIP4 | String | ZIP 4 Code of Location. ZIP 4 not given for Move file   data (previous Establishment locations). | = Company[ZIP4]    OR   = nan




</body>

</html>


<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/stf45/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

<link rel=themeData
href="file:///C:/Users/stf45/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/stf45/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=EN-US style='tab-interval:.5in;word-wrap:break-word'>


<h3>Appendix M: DunsMove <o:p></o:p></h3>

<p class=MsoNoSpacing><a name="_Hlk137212280"><u>Dataset name</u>:<b> DunsMove <o:p></o:p></b></a></p>

<p class=MsoNoSpacing><span style='mso-bookmark:_Hlk137212280'><u>Filename</u>:
DunsMoveYYYYMMDD.txt <o:p></o:p></span></p>

<p class=MsoNoSpacing><span style='mso-bookmark:_Hlk137212280'><u>Number of
records</u>: 32,967,561 <o:p></o:p></span></p>

<p class=MsoNoSpacing><span style='mso-bookmark:_Hlk137212280'><u>Number of
unique DunsMoves</u>: 32,967,561<o:p></o:p></span></p>

<p class=MsoNoSpacing><span style='mso-bookmark:_Hlk137212280'><u>Number of
unique DunsNumbers</u>: 30,034,194<o:p></o:p></span></p>

<p class=MsoNoSpacing><span style='mso-bookmark:_Hlk137212280'><u>Number of
columns</u>: 5<o:p></o:p></span></p>

<p class=MsoNoSpacing><span style='mso-bookmark:_Hlk137212280'><u>Columns</u>:
DunsMove, DunsNumber, AddressID, GcFirstYear, GcLastYear<o:p></o:p></span></p>

<span style='mso-bookmark:_Hlk137212280'></span>

<p class=MsoNoSpacing><u>Python file that generated this file</u>: create_geocoding.py<o:p></o:p></p>

<h3><o:p>&nbsp;</o:p></h3>

<p class=MsoNoSpacing><span style='font-size:10.0pt'>DunsMove Variable List<o:p></o:p></span></p>



Variable | Type | Description | Formula
-- | -- | -- | --
DunsMove | Text | 11-digit unique identifier for each Establishment   Location. MoveNum and the number 10 are added as integers, which is   then concatenated with the DunsNumber | = 10+MoveNum+DunsNumber           Ex:    MoveNum = 3   DunsNumber = 000011111   DunsMove = 13000011111       Ex 2:   MoveNum = 10   DunsNumber = 000011111   DunsMove = 20000011111
DunsNumber | String | 9-digit unique identifier for each Establishment. Not   unique in this dataset, as Establishments retain the same DunsNumber when   they move locations. | = Company[DunsNumber]    OR    = Move[DunsNumber]
AddressID | Integer | Unique ID for combination of GcAddress, GcCity,   GcState, GcZIP, GcZIP4 | "A" + nine-digit string, i.e. A000000001
GcFirstYear | Integer | First year Establishment is at a particular location.   The year that Establishment moves (Move[MoveYear]) is the last year in that   location. The following year is the first year at the location that it moved   to. | First location = Misc[Firstyear] +1   OR   Subsequent locations = Misc[MoveYear] of   previous location +1
GcLastYear | Integer | Last year Establishment is at a particular location.   The year that Establishment moves (Move[MoveYear]) is the last year in that   location. The following year is the first year at the location that it moved   to. | Last location = Misc[LastYear]   Previous locations = Move[MoveYear]




</body>

</html>
