### ISSUE TITLE
NETS 2022 Categorization

### ISSUE THREAD

**Issue by sjmelly** [Drexel-UHC/NETS#20]

**Comment by stfran22** [comment]
datasets completed so far:
Classification Input
Classification Input (subset for Python)
Classification Input (subset for SAS)

**Comment by stfran22** [comment]
I've added an excel report NETS2022_classified_long_report.xlsx to `Z:\UHC_Data\NETS_UHC\NETS2022\Data` which contains some descriptives of the ClassifiedLong dataset. The first sheet has Base Group counts for 2022, and 2019, as well as the fraction difference (2019->2022). Fraction differences range from 0.033 - 1.77 and the mean is 0.21.

**Comment by stfran22** [comment]
Categorization step has been done for a while so I'm going to close.
