### ISSUE TITLE
Create NETS 2022 dataset for geocoding

### ISSUE THREAD

**Issue by sjmelly** [Drexel-UHC/NETS#21]
Include locations with SICs used to create categories

**Comment by stfran22** [comment]
File Addresses20231027.txt has been created and is in \UHC_Data\NETS_UHC\NETS2022\Data\Final. Intermediate files gecoding_1_20231027.txt and gecoding_2_20231027.txt are in \UHC_Data\NETS_UHC\NETS2022\Data\Intermediate. 

Closing as complete. Next step is geocoding #22.
