### ISSUE TITLE
Geocode NETS 2022

### ISSUE THREAD

**Issue by sjmelly** [Drexel-UHC/NETS#22]

**Comment by stfran22** [comment]
NETS2022 geocoded with 25,963,769 records. Linked UHCMatchCodeRank from R:\DeansOffice\Projects\MESA\MESA_Neigh_Age\Documentation\MatchCodeRank.gdb\addr_type_matchcoderank. Removed 1 record (AddressID A020614575) as it was geocoded to Puerto Rico. Now n=25,963,769.

Next steps:

-  join Z:\UHC_Data\Census2010\Geodatabases\Census2010_US20230929.gdb\CT_2010_ContUSlandRepairAlbers for 2010 census tracts 
- join Z:\UHC_Data\Census2010\Geodatabases\Census2010_US.gdb\ZCTA_2010_ContUS for ZCTAs. 

@sjmelly might people be interested in 2020 tracts and zctas as well?

**Comment by stfran22** [comment]
I set GEOID10 to null if ct10_distance > 1000 and did the same with ZCTA5C310 and zcta10_distance. DunsLocation20231207.txt reflects these changes and has been added to the NETS2022 database as well as Z:\UHC_Data\NETS_UHC\NETS2022\Data\Final. Closing this issue as geocoding is complete and final dataset has been created.
