### ISSUE TITLE
change repository's "about" section

### ISSUE THREAD

**Issue by stfran22** [Drexel-UHC/NETS#24]
@sjmelly I just want to remove the "2019" from the about section of the repo (top right corner), as I now have different branches for different vintages of NETS. I don't have a gear symbol next to the about section so I'm guessing I don't have the ability to do this.

**Comment by sjmelly** [comment]
I was able to make the change. I didn't see a way to add other people to be able to manage the repository

**Comment by stfran22** [comment]
I believe because the repo is associated with the UHC organization, you'd have to change admin status at the organization level, not at the repository level.
