### ISSUE TITLE
Re-process NETS/BEDDN tract/zcta level datasets using Hierarchy

### ISSUE THREAD

**Issue by stfran22** [Drexel-UHC/NETS#32]
Reprocess using hierarchy to ensure each DunsYear is only assigned to the Base Group with the lowest value in the Hierarchy variable.

**Comment by stfran22** [comment]
Reprocessing complete. @kam642 @sjmelly I saved files in separate folders in Z:\UHC_Data\NETS_UHC\NETS2022\Data\Final. I created two tables comparing the hierarchy and non hierarchy versions on a subset of the tract level BEDDN densities (subset for philly tracts, one file 2010, the other 2022): `Z:\UHC_Data\NETS_UHC\NETS2022\Data\Checks\hierarchy_nonhierarchy_phl_diffYYYY.csv`. Question - should we only hold the hierarchy version in the azure database?

**Comment by kam642** [comment]
@stfran22 @sjmelly I'm going to vote to only keep hierarchy on Azure.

**Comment by stfran22** [comment]
@jannettim just drawing your attention to this. Not sure where you're at with re-uploading, but let's use these new "hierarchy" versions of tract and zcta-level measures. We can use the same tract id and zcta id tables.

**Comment by jannettim** [comment]
@stfran22 I haven't had a chance to move forward with actually uploading anything. But I think I have the files ready to upload.
