### ISSUE TITLE
Geocode NETS 2019

### ISSUE THREAD

**Issue by sjmelly** [Drexel-UHC/NETS#6]
Using ArcGISPro  and Business Analyst 2021 Address Locator geocode unique NETS addresses (GcAddress, GcCity GcState GcZIP & GcZIP4) in contiguous US. Use ADDRESSID to link geocoding results  to NETS DUNSMove dataset

**Comment by sjmelly** [comment]
Parameters for geocoding:
![Image](https://github.com/Drexel-UHC/NETS/assets/16820816/1ce6bdea-5c2c-467c-8cf5-2aefc7f3aacd)

**Comment by sjmelly** [comment]
Use Geocoding Data for ArGISPro\USA.loc

![Image](https://github.com/Drexel-UHC/NETS/assets/16820816/b64cfc5f-1b54-4e61-a441-b38e9a9b7286)

**Comment by sjmelly** [comment]
James provided frequencies of level of accuracy for NETS 2014 geocoding in \Projects\NETS\Documentation\fromJamesQuinn\ nets_tall_v1_20220913.pdf We should compare our results to these. See \Projects\NETS\Documentation\NETSGeocodingChecks20230607.docx

**Comment by stfran22** [comment]
@sjmelly Just added the Addresses20230608 (formerly GeocodingInput) file to my Arc project, and for some reason it has added two columns that don't exist in the file: AddressID_X and AddressID_Y. Any idea why this is happening? Should I just delete them?

**Comment by sjmelly** [comment]
Strange. Do they have values? Are you adding a .csv using a schema.ini file?  A key issue is that ZIP and ZIP + 4 are read as text

**Comment by stfran22** [comment]
They do and yes I created a schema file for the zip and zip4 before loading. The values are all about -134.9 longitude and -74.9 latitude.

**Comment by sjmelly** [comment]
I've been just using the Add Data\Data Add data to the map to add tables for example \Projects\NETS\Data\NETS2019_Python\SMExample\nets2019geocodingswarthmorev2.txt and I don't get AddressID_X and Y
What happens when you try adding that file?

**Comment by stfran22** [comment]
There was no option to reduce fields in the Table to SAS tool. Had to run Table to Table first and create a subset as a gdb table first.

**Comment by sjmelly** [comment]
You can use the field view to select the fields you want visible in your map layer, then use the map layer as the Input Table in the Table to SAS tool. You could also use the Make Table View tool (in model builder or with Python) to make a table view with selected attributes as the input to the Table to SAS tool. I've put these notes in the OneDrive\ArcGISProCodeExamples_Tricks folder https://drexel0-my.sharepoint.com/:w:/r/personal/sjm389_drexel_edu/Documents/ArcGISProCodeExamples_Tips/[ArcGISProTabletoSAS.docx](https://drexel0-my.sharepoint.com/:w:/r/personal/sjm389_drexel_edu/Documents/ArcGISProCodeExamples_Tips/ArcGISProTabletoSAS.docx?d=w82ff8988b4394b99a7b8fc583eabd910&csf=1&web=1&e=YykS7Z)?d=w82ff8988b4394b99a7b8fc583eabd910&csf=1&web=1&e=YykS7Z

**Comment by stfran22** [comment]
4,427 records were not geocoded (DisplayX, DisplayY = 0,0). Records were distributed across 47/49 states (including DC, excluding AK and HI)

**Comment by stfran22** [comment]
schema for the NETS_locs final attribute table. There will be a spatial version of this and a tabular version of this:
- Address ID
- displayX
- displayY
- projX
- projY
- matchcoderank
- addr_type
- status
- score
- GEOID10

**Next Steps**
1. create gdb table in NETS_locs.gdb: NETS_locs_matchfreqs20230620
- status
- score
- addr_type
- addressID

2. join UHCmatchcoderank table (csv) to NETS_locs_matchfreqs20230620
3. join NETS_locs_matchfreqs20230620 to feature class NETS_locs_CT10_20230620 (this is the result of the spatial join of 2010 tracts to NETS locs)

**Comment by stfran22** [comment]
Did we decide to leave in unmatched records for the spatial join or am I only removing the record that was geocoded to PR?

**Comment by sjmelly** [comment]
It is good practice to exclude records from a spatial dataset that have no location. Some ArcGISPro tools may give you errors if you use them on a dataset with empty records. In this case after you do the spatial join you will split the dataset up by UTMZone before doing further spatial analyses. You will be effectively removing the unmatched records at the step when you split them by UTM Zone

**Comment by stfran22** [comment]
@sjmelly Just went back and made sure the 4,427 records that were not able to be geocoded, as well as the single record that was geocoded to be in puerto rico (AddressID A017810708) have been removed from the spatial and tabular final versions of DunsLocation.

**Comment by stfran22** [comment]
> Great. By tabular final version do you mean both \Projects\NETS\Data\NETS2019_Python\DunsLocation20230919.csv and the table in Azure?

Correct! New n=23,250,232.
