### ISSUE TITLE
Split NETS spatial dataset into overlapping UTM Zones

### ISSUE THREAD

**Issue by sjmelly** [Drexel-UHC/NETS#8]
Use 15 km overlap - same as MESA Built Environment Methods
Some NETS locations will be in two overlapping UTM Zones

**Comment by stfran22** [comment]
This is done and has been checked. Sum of records of all UTM split files, with duplicates removed, is equal to number of records in full DunsLocations file - 4427 (number of records with null X,Y). @sjmelly  should I just remove the records with null x,y in the full file?

**Comment by sjmelly** [comment]
Yes remove records with null X, Y from spatial datasets. Having records with no geometry in a spatial dataset could cause errors with some ArcGISPro tools. Did we decide that these spatial datasets will be saved to the server in \Projects\NETS\Data\NETS2019_Spatial ?

**Comment by stfran22** [comment]
Done and done. I think we can close this issue.

**Comment by stfran22** [comment]
done!
